services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatWorkExternalContactStatsBundle\Command\:
    resource: '../../Command/'
  WechatWorkExternalContactStatsBundle\Repository\:
    resource: '../../Repository/'
  WechatWorkExternalContactStatsBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
  WechatWorkExternalContactStatsBundle\Service\:
    resource: '../../Service/'
