services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # DataFixtures
  WechatWorkExternalContactStatsBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    tags: ['doctrine.fixture.orm']